name: py38_quadroots
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.0.221
  - jupyterlab=2.2.6
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pandas=1.2.0
  - pip=20.3.3
  - python=3.8.5
  - pytorch=1.7.1
